version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: agrotique_db
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - agrotique_net

  redis:
    image: redis:7-alpine
    container_name: agrotique_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - agrotique_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agrotique_backend
    env_file:
      - .env.dev
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        sleep 5 &&
        alembic revision --autogenerate -m 'Initial migration with users, gardens, and plants' &&
        alembic upgrade head &&
        echo 'Database is ready. Starting server.' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    networks:
      - agrotique_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: agrotique_pgadmin
    env_file:
      - .env.dev
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@agrotique.com"
      PGADMIN_DEFAULT_PASSWORD: "admin_password"
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - agrotique_net

networks:
  agrotique_net:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
