apiVersion: v1
kind: Namespace
metadata:
  name: agrotique
  labels:
    name: agrotique
    app: garden-planner
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: agrotique-quota
  namespace: agrotique
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "20"
    configmaps: "20" 