apiVersion: v1
kind: Secret
metadata:
  name: agrotique-secrets
  namespace: agrotique
type: Opaque
data:
  # These are base64 encoded values - replace with actual values
  SECRET_KEY: <base64-encoded-secret-key>
  POSTGRES_PASSWORD: <base64-encoded-postgres-password>
  REDIS_PASSWORD: <base64-encoded-redis-password>
  GRAFANA_PASSWORD: <base64-encoded-grafana-password>
  BACKUP_ENCRYPTION_KEY: <base64-encoded-backup-encryption-key>
  SLACK_WEBHOOK_URL: <base64-encoded-slack-webhook-url>
---
apiVersion: v1
kind: Secret
metadata:
  name: ssl-certificates
  namespace: agrotique
type: kubernetes.io/tls
data:
  # Replace with actual base64 encoded certificates
  tls.crt: <base64-encoded-certificate>
  tls.key: <base64-encoded-private-key> 